
os: osx

osx_image: xcode13.4

notifications:
  email:
    recipients:
      - humberto.a.sanchez.ii@gmail.com
    on_success: change # default: change
    on_failure: always # default: always

cache: pip

before_install:
  - brew list
  - brew upgrade python
  - curl https://bootstrap.pypa.io/get-pip.py | python3

# command to install dependencies
install:
  - python3 --version
  - pip install -r requirements.txt


# command to run tests
script: ${TRAVIS_BUILD_DIR}/scripts/runtests.sh
